let courses = [
    {
        "courseName": "IT2020/01",
        "firstLeader": {"firstName": "Thomas", "lastName": "Bauer", "gender": "m"},
        "secondLeader": {"firstName": "Maria", "lastName": "Klein", "gender": "f"},
        "students": [
            {"firstName": "Leon", "lastName": "Wagner", "profession": "FIAE", "status": "grün", "applications": 12},
            {"firstName": "Emma", "lastName": "Koch", "profession": "FISI", "status": "grün", "applications": 19},
            {"firstName": "Felix", "lastName": "Richter", "profession": "FIDM", "status": "gelb", "applications": 7},
            {"firstName": "Hannah", "lastName": "Groß", "profession": "FIAE", "status": "grün", "applications": 15},
            {"firstName": "Jan", "lastName": "König", "profession": "FISI", "status": "rot", "applications": 5},
            {"firstName": "Paula", "lastName": "Pfeiffer", "profession": "FIDM", "status": "gelb", "applications": 9},
            {"firstName": "Moritz", "lastName": "Hahn", "profession": "FIAE", "status": "grün", "applications": 18},
            {"firstName": "Lara", "lastName": "Engel", "profession": "FISI", "status": "grün", "applications": 14},
            {"firstName": "Simon", "lastName": "Frank", "profession": "FIDM", "status": "gelb", "applications": 11},
            {"firstName": "Julia", "lastName": "Krause", "profession": "FIAE", "status": "grün", "applications": 20},
            {"firstName": "Till", "lastName": "Vogt", "profession": "FISI", "status": "rot", "applications": 6},
            {"firstName": "Lea", "lastName": "Kaiser", "profession": "FIDM", "status": "grün", "applications": 16},
            {"firstName": "Nico", "lastName": "Horn", "profession": "FIAE", "status": "gelb", "applications": 10},
            {"firstName": "Mara", "lastName": "Sommer", "profession": "FISI", "status": "grün", "applications": 17},
            {"firstName": "Erik", "lastName": "Böhm", "profession": "FIDM", "status": "gelb", "applications": 8},
            {"firstName": "Nora", "lastName": "Weiß", "profession": "FIAE", "status": "rot", "applications": 4},
            {"firstName": "Theo", "lastName": "Scholz", "profession": "FISI", "status": "grün", "applications": 13},
            {"firstName": "Maya", "lastName": "Friedrich", "profession": "FIDM", "status": "grün", "applications": 19},
            {"firstName": "Robin", "lastName": "Jansen", "profession": "FIAE", "status": "gelb", "applications": 12},
            {"firstName": "Ida", "lastName": "Stein", "profession": "FISI", "status": "grün", "applications": 21}
        ]
    },
    {
        "courseName": "IT2020/07",
        "firstLeader": {"firstName": "Klaus", "lastName": "Schneider", "gender": "m"},
        "secondLeader": {"firstName": "Petra", "lastName": "Wolf", "gender": "f"},
        "students": [
            {"firstName": "Lukas", "lastName": "Schäfer", "profession": "FISI", "status": "grün", "applications": 16},
            {"firstName": "Mia", "lastName": "Becker", "profession": "FIAE", "status": "rot", "applications": 4},
            {"firstName": "Noah", "lastName": "Hoffmann", "profession": "FIDM", "status": "gelb", "applications": 9},
            {"firstName": "Amelie", "lastName": "Graf", "profession": "FIAE", "status": "grün", "applications": 18},
            {"firstName": "Finn", "lastName": "Baum", "profession": "FISI", "status": "gelb", "applications": 11},
            {"firstName": "Zoe", "lastName": "Ritter", "profession": "FIDM", "status": "grün", "applications": 14},
            {"firstName": "Milan", "lastName": "Berg", "profession": "FIAE", "status": "rot", "applications": 7},
            {"firstName": "Mila", "lastName": "Winter", "profession": "FISI", "status": "grün", "applications": 20},
            {"firstName": "Anton", "lastName": "Fuchs", "profession": "FIDM", "status": "gelb", "applications": 10},
            {"firstName": "Clara", "lastName": "Vogel", "profession": "FIAE", "status": "grün", "applications": 15},
            {"firstName": "Oskar", "lastName": "Kraus", "profession": "FISI", "status": "grün", "applications": 17},
            {"firstName": "Lia", "lastName": "Berger", "profession": "FIDM", "status": "rot", "applications": 5},
            {"firstName": "Leonard", "lastName": "Haas", "profession": "FIAE", "status": "gelb", "applications": 12},
            {"firstName": "Emilia", "lastName": "Schubert", "profession": "FISI", "status": "grün", "applications": 19},
            {"firstName": "Matteo", "lastName": "Lorenz", "profession": "FIDM", "status": "gelb", "applications": 8},
            {"firstName": "Lina", "lastName": "Kuhn", "profession": "FIAE", "status": "grün", "applications": 16},
            {"firstName": "Emil", "lastName": "Auer", "profession": "FISI", "status": "rot", "applications": 6},
            {"firstName": "Charlotte", "lastName": "Bach", "profession": "FIDM", "status": "grün", "applications": 13},
            {"firstName": "Greta", "lastName": "Lindner", "profession": "FIAE", "status": "gelb", "applications": 11},
            {"firstName": "Jakob", "lastName": "Brandt", "profession": "FISI", "status": "grün", "applications": 22}
        ]
    },
    {
        "courseName": "IT2021/01",
        "firstLeader": {"firstName": "Andreas", "lastName": "Lehmann", "gender": "m"},
        "secondLeader": {"firstName": "Sandra", "lastName": "Vogel", "gender": "f"},
        "students": [
            {"firstName": "Sophie", "lastName": "Kraus", "profession": "FIAE", "status": "grün", "applications": 21},
            {"firstName": "Paul", "lastName": "Zimmermann", "profession": "FISI", "status": "gelb", "applications": 11},
            {"firstName": "Laura", "lastName": "Braun", "profession": "FIDM", "status": "grün", "applications": 14},
            {"firstName": "Elias", "lastName": "Hofmann", "profession": "FIAE", "status": "rot", "applications": 4},
            {"firstName": "Johanna", "lastName": "Pohl", "profession": "FISI", "status": "grün", "applications": 18},
            {"firstName": "David", "lastName": "Voss", "profession": "FIDM", "status": "gelb", "applications": 9},
            {"firstName": "Ella", "lastName": "Seidel", "profession": "FIAE", "status": "grün", "applications": 16},
            {"firstName": "Felix", "lastName": "Schuster", "profession": "FISI", "status": "grün", "applications": 19},
            {"firstName": "Mia", "lastName": "Körber", "profession": "FIDM", "status": "rot", "applications": 5},
            {"firstName": "Luis", "lastName": "Ott", "profession": "FIAE", "status": "gelb", "applications": 12},
            {"firstName": "Anna", "lastName": "Seifert", "profession": "FISI", "status": "grün", "applications": 17},
            {"firstName": "Ben", "lastName": "Albrecht", "profession": "FIDM", "status": "gelb", "applications": 10},
            {"firstName": "Emma", "lastName": "Lenz", "profession": "FIAE", "status": "grün", "applications": 20},
            {"firstName": "Jonas", "lastName": "Wenzel", "profession": "FISI", "status": "rot", "applications": 6},
            {"firstName": "Lena", "lastName": "Petersen", "profession": "FIDM", "status": "grün", "applications": 15},
            {"firstName": "Maximilian", "lastName": "Bauer", "profession": "FIAE", "status": "gelb", "applications": 8},
            {"firstName": "Hannah", "lastName": "Riedel", "profession": "FISI", "status": "grün", "applications": 13},
            {"firstName": "Noah", "lastName": "Franke", "profession": "FIDM", "status": "grün", "applications": 18},
            {"firstName": "Lea", "lastName": "Schreiber", "profession": "FIAE", "status": "gelb", "applications": 11},
            {"firstName": "Tim", "lastName": "Geiger", "profession": "FISI", "status": "grün", "applications": 22}
        ]
    },
    {
        "courseName": "IT2021/07",
        "firstLeader": {"firstName": "Michael", "lastName": "Krüger", "gender": "m"},
        "secondLeader": {"firstName": "Julia", "lastName": "Hartmann", "gender": "f"},
        "students": [
            {"firstName": "Tim", "lastName": "Werner", "profession": "FISI", "status": "grün", "applications": 17},
            {"firstName": "Hannah", "lastName": "Lang", "profession": "FIAE", "status": "rot", "applications": 5},
            {"firstName": "Ben", "lastName": "Klein", "profession": "FIDM", "status": "gelb", "applications": 10},
            {"firstName": "Emily", "lastName": "Stein", "profession": "FIAE", "status": "grün", "applications": 19},
            {"firstName": "Leon", "lastName": "Arnold", "profession": "FISI", "status": "gelb", "applications": 12},
            {"firstName": "Sofia", "lastName": "Wolff", "profession": "FIDM", "status": "grün", "applications": 16},
            {"firstName": "Samuel", "lastName": "Brandt", "profession": "FIAE", "status": "rot", "applications": 7},
            {"firstName": "Mila", "lastName": "Simon", "profession": "FISI", "status": "grün", "applications": 20},
            {"firstName": "Henry", "lastName": "Böhm", "profession": "FIDM", "status": "gelb", "applications": 9},
            {"firstName": "Lara", "lastName": "Michel", "profession": "FIAE", "status": "grün", "applications": 15},
            {"firstName": "Niklas", "lastName": "König", "profession": "FISI", "status": "grün", "applications": 18},
            {"firstName": "Clara", "lastName": "Keller", "profession": "FIDM", "status": "rot", "applications": 4},
            {"firstName": "Julian", "lastName": "Jung", "profession": "FIAE", "status": "gelb", "applications": 11},
            {"firstName": "Amelie", "lastName": "Roth", "profession": "FISI", "status": "grün", "applications": 17},
            {"firstName": "Fabian", "lastName": "Krause", "profession": "FIDM", "status": "gelb", "applications": 8},
            {"firstName": "Maja", "lastName": "Huber", "profession": "FIAE", "status": "grün", "applications": 14},
            {"firstName": "Luca", "lastName": "Schmitz", "profession": "FISI", "status": "rot", "applications": 6},
            {"firstName": "Frieda", "lastName": "Voigt", "profession": "FIDM", "status": "grün", "applications": 13},
            {"firstName": "Theo", "lastName": "Winkler", "profession": "FIAE", "status": "gelb", "applications": 10},
            {"firstName": "Isabella", "lastName": "Groß", "profession": "FISI", "status": "grün", "applications": 21}
        ]
    },
    {
        "courseName": "IT2022/01",
        "firstLeader": {"firstName": "Stefan", "lastName": "Neumann", "gender": "m"},
        "secondLeader": {"firstName": "Claudia", "lastName": "Möller", "gender": "f"},
        "students": [
            {"firstName": "Jana", "lastName": "Schulz", "profession": "FIAE", "status": "grün", "applications": 20},
            {"firstName": "Max", "lastName": "Friedrich", "profession": "FISI", "status": "gelb", "applications": 8},
            {"firstName": "Lena", "lastName": "Berger", "profession": "FIDM", "status": "grün", "applications": 15},
            {"firstName": "Oliver", "lastName": "Herzog", "profession": "FIAE", "status": "rot", "applications": 5},
            {"firstName": "Sarah", "lastName": "Vogt", "profession": "FISI", "status": "grün", "applications": 18},
            {"firstName": "Moritz", "lastName": "Bender", "profession": "FIDM", "status": "gelb", "applications": 11},
            {"firstName": "Nele", "lastName": "Kaiser", "profession": "FIAE", "status": "grün", "applications": 16},
            {"firstName": "Tobias", "lastName": "Lehmann", "profession": "FISI", "status": "grün", "applications": 19},
            {"firstName": "Paula", "lastName": "Sauer", "profession": "FIDM", "status": "rot", "applications": 4},
            {"firstName": "Simon", "lastName": "Engel", "profession": "FIAE", "status": "gelb", "applications": 12},
            {"firstName": "Julia", "lastName": "Böttcher", "profession": "FISI", "status": "grün", "applications": 17},
            {"firstName": "Erik", "lastName": "Hahn", "profession": "FIDM", "status": "gelb", "applications": 9},
            {"firstName": "Klara", "lastName": "Kunz", "profession": "FIAE", "status": "grün", "applications": 14},
            {"firstName": "Robin", "lastName": "Schröder", "profession": "FISI", "status": "rot", "applications": 6},
            {"firstName": "Ida", "lastName": "Horn", "profession": "FIDM", "status": "grün", "applications": 13},
            {"firstName": "Vincent", "lastName": "Fiedler", "profession": "FIAE", "status": "gelb", "applications": 10},
            {"firstName": "Marlene", "lastName": "Nagel", "profession": "FISI", "status": "grün", "applications": 20},
            {"firstName": "Anton", "lastName": "Ziegler", "profession": "FIDM", "status": "gelb", "applications": 8},
            {"firstName": "Mira", "lastName": "Pfeiffer", "profession": "FIAE", "status": "grün", "applications": 15},
            {"firstName": "Adrian", "lastName": "Förster", "profession": "FISI", "status": "grün", "applications": 22}
        ]
    },
    {
        "courseName": "IT2022/07",
        "firstLeader": {"firstName": "Daniel", "lastName": "Schmitt", "gender": "m"},
        "secondLeader": {"firstName": "Katrin", "lastName": "Meier", "gender": "f"},
        "students": [
            {"firstName": "David", "lastName": "Walter", "profession": "FISI", "status": "grün", "applications": 18},
            {"firstName": "Nina", "lastName": "Peters", "profession": "FIAE", "status": "rot", "applications": 6},
            {"firstName": "Erik", "lastName": "Schwarz", "profession": "FIDM", "status": "gelb", "applications": 11},
            {"firstName": "Lisa", "lastName": "Heinz", "profession": "FIAE", "status": "grün", "applications": 17},
            {"firstName": "Tom", "lastName": "Busch", "profession": "FISI", "status": "gelb", "applications": 10},
            {"firstName": "Emely", "lastName": "Stark", "profession": "FIDM", "status": "grün", "applications": 14},
            {"firstName": "Lukas", "lastName": "Sommer", "profession": "FIAE", "status": "rot", "applications": 5},
            {"firstName": "Marie", "lastName": "Gold", "profession": "FISI", "status": "grün", "applications": 19},
            {"firstName": "Jacob", "lastName": "Weise", "profession": "FIDM", "status": "gelb", "applications": 9},
            {"firstName": "Elena", "lastName": "Bayer", "profession": "FIAE", "status": "grün", "applications": 16},
            {"firstName": "Rafael", "lastName": "Grimm", "profession": "FISI", "status": "grün", "applications": 20},
            {"firstName": "Sophia", "lastName": "Eckert", "profession": "FIDM", "status": "rot", "applications": 4},
            {"firstName": "Constantin", "lastName": "Jäger", "profession": "FIAE", "status": "gelb", "applications": 12},
            {"firstName": "Lilly", "lastName": "Franke", "profession": "FISI", "status": "grün", "applications": 15},
            {"firstName": "Mattis", "lastName": "Bock", "profession": "FIDM", "status": "gelb", "applications": 8},
            {"firstName": "Frieda", "lastName": "Baum", "profession": "FIAE", "status": "grün", "applications": 18},
            {"firstName": "Leopold", "lastName": "Henkel", "profession": "FISI", "status": "rot", "applications": 7},
            {"firstName": "Romy", "lastName": "Pfeifer", "profession": "FIDM", "status": "grün", "applications": 13},
            {"firstName": "Valentin", "lastName": "Runge", "profession": "FIAE", "status": "gelb", "applications": 11},
            {"firstName": "Alma", "lastName": "Brenner", "profession": "FISI", "status": "grün", "applications": 21}
        ]
    },
    {
        "courseName": "IT2023/01",
        "firstLeader": {"firstName": "Max", "lastName": "Mustermann", "gender": "m"},
        "secondLeader": {"firstName": "Erika", "lastName": "Musterfrau", "gender": "f"},
        "students": [
            {"firstName": "Anna", "lastName": "Schmidt", "profession": "FIAE", "status": "grün", "applications": 15},
            {"firstName": "Tom", "lastName": "Meyer", "profession": "FISI", "status": "gelb", "applications": 8},
            {"firstName": "Lisa", "lastName": "Müller", "profession": "FIDM", "status": "rot", "applications": 3},
            {"firstName": "Jonas", "lastName": "Weber", "profession": "FIAE", "status": "grün", "applications": 22},
            {"firstName": "Sarah", "lastName": "Fischer", "profession": "FISI", "status": "grün", "applications": 18},
            {"firstName": "Felix", "lastName": "Wagner", "profession": "FIDM", "status": "gelb", "applications": 10},
            {"firstName": "Laura", "lastName": "Becker", "profession": "FIAE", "status": "grün", "applications": 16},
            {"firstName": "Lukas", "lastName": "Schulz", "profession": "FISI", "status": "rot", "applications": 5},
            {"firstName": "Emma", "lastName": "Hoffmann", "profession": "FIDM", "status": "gelb", "applications": 9},
            {"firstName": "Paul", "lastName": "Koch", "profession": "FIAE", "status": "grün", "applications": 19},
            {"firstName": "Sophie", "lastName": "Richter", "profession": "FISI", "status": "grün", "applications": 14},
            {"firstName": "Maximilian", "lastName": "Schröder", "profession": "FIDM", "status": "gelb", "applications": 11},
            {"firstName": "Hannah", "lastName": "Neumann", "profession": "FIAE", "status": "rot", "applications": 6},
            {"firstName": "Leon", "lastName": "Krause", "profession": "FISI", "status": "grün", "applications": 17},
            {"firstName": "Mia", "lastName": "Lange", "profession": "FIDM", "status": "gelb", "applications": 12},
            {"firstName": "Noah", "lastName": "Schmitt", "profession": "FIAE", "status": "grün", "applications": 20},
            {"firstName": "Lena", "lastName": "Werner", "profession": "FISI", "status": "rot", "applications": 4},
            {"firstName": "David", "lastName": "Krüger", "profession": "FIDM", "status": "grün", "applications": 13},
            {"firstName": "Emily", "lastName": "Hartmann", "profession": "FIAE", "status": "gelb", "applications": 9},
            {"firstName": "Finn", "lastName": "Zimmermann", "profession": "FISI", "status": "grün", "applications": 21}
        ]
    },
    {
        "courseName": "IT2023/07",
        "firstLeader": {"firstName": "Peter", "lastName": "Maier", "gender": "m"},
        "secondLeader": {"firstName": "Sabine", "lastName": "Roth", "gender": "f"},
        "students": [
            {"firstName": "Marie", "lastName": "Jung", "profession": "FIAE", "status": "grün", "applications": 19},
            {"firstName": "Finn", "lastName": "Lange", "profession": "FISI", "status": "gelb", "applications": 9},
            {"firstName": "Clara", "lastName": "Frank", "profession": "FIDM", "status": "grün", "applications": 16},
            {"firstName": "Henry", "lastName": "Braun", "profession": "FIAE", "status": "rot", "applications": 5},
            {"firstName": "Ella", "lastName": "Klein", "profession": "FISI", "status": "grün", "applications": 18},
            {"firstName": "Oskar", "lastName": "Winter", "profession": "FIDM", "status": "gelb", "applications": 11},
            {"firstName": "Mila", "lastName": "Seidel", "profession": "FIAE", "status": "grün", "applications": 15},
            {"firstName": "Anton", "lastName": "Vogel", "profession": "FISI", "status": "grün", "applications": 20},
            {"firstName": "Ida", "lastName": "Kaiser", "profession": "FIDM", "status": "rot", "applications": 4},
            {"firstName": "Leonard", "lastName": "Graf", "profession": "FIAE", "status": "gelb", "applications": 12},
            {"firstName": "Charlotte", "lastName": "Bergmann", "profession": "FISI", "status": "grün", "applications": 17},
            {"firstName": "Theo", "lastName": "Schuster", "profession": "FIDM", "status": "gelb", "applications": 10},
            {"firstName": "Greta", "lastName": "Ott", "profession": "FIAE", "status": "grün", "applications": 14},
            {"firstName": "Emil", "lastName": "Busch", "profession": "FISI", "status": "rot", "applications": 6},
            {"firstName": "Lina", "lastName": "Schubert", "profession": "FIDM", "status": "grün", "applications": 13},
            {"firstName": "Jakob", "lastName": "Voigt", "profession": "FIAE", "status": "gelb", "applications": 8},
            {"firstName": "Emilia", "lastName": "Herrmann", "profession": "FISI", "status": "grün", "applications": 19},
            {"firstName": "Matteo", "lastName": "Keller", "profession": "FIDM", "status": "gelb", "applications": 11},
            {"firstName": "Lia", "lastName": "Simon", "profession": "FIAE", "status": "grün", "applications": 16},
            {"firstName": "Milan", "lastName": "Winkler", "profession": "FISI", "status": "grün", "applications": 22}
        ]
    },
    {
        "courseName": "IT2024/01",
        "firstLeader": {"firstName": "Hans", "lastName": "Müller", "gender": "m"},
        "secondLeader": {"firstName": "Anna", "lastName": "Schmidt", "gender": "f"},
        "students": [
            {"firstName": "Oliver", "lastName": "Schulze", "profession": "FISI", "status": "grün", "applications": 14},
            {"firstName": "Sophia", "lastName": "Hoffmann", "profession": "FIAE", "status": "rot", "applications": 5},
            {"firstName": "Luis", "lastName": "Becker", "profession": "FIDM", "status": "gelb", "applications": 12},
            {"firstName": "Isabella", "lastName": "Arnold", "profession": "FIAE", "status": "grün", "applications": 19},
            {"firstName": "Leo", "lastName": "Werner", "profession": "FISI", "status": "gelb", "applications": 10},
            {"firstName": "Amelie", "lastName": "Fuchs", "profession": "FIDM", "status": "grün", "applications": 16},
            {"firstName": "Samuel", "lastName": "Lorenz", "profession": "FIAE", "status": "rot", "applications": 6},
            {"firstName": "Johanna", "lastName": "Berger", "profession": "FISI", "status": "grün", "applications": 18},
            {"firstName": "Elias", "lastName": "Haas", "profession": "FIDM", "status": "gelb", "applications": 11},
            {"firstName": "Nele", "lastName": "Albrecht", "profession": "FIAE", "status": "grün", "applications": 15},
            {"firstName": "Julian", "lastName": "Seifert", "profession": "FISI", "status": "grün", "applications": 20},
            {"firstName": "Klara", "lastName": "Petersen", "profession": "FIDM", "status": "rot", "applications": 4},
            {"firstName": "Vincent", "lastName": "Riedel", "profession": "FIAE", "status": "gelb", "applications": 13},
            {"firstName": "Marlene", "lastName": "Bauer", "profession": "FISI", "status": "grün", "applications": 17},
            {"firstName": "Robin", "lastName": "Geiger", "profession": "FIDM", "status": "gelb", "applications": 9},
            {"firstName": "Maja", "lastName": "Franke", "profession": "FIAE", "status": "grün", "applications": 14},
            {"firstName": "Adrian", "lastName": "Schreiber", "profession": "FISI", "status": "rot", "applications": 7},
            {"firstName": "Frieda", "lastName": "Wenzel", "profession": "FIDM", "status": "grün", "applications": 12},
            {"firstName": "Valentin", "lastName": "Lenz", "profession": "FIAE", "status": "gelb", "applications": 10},
            {"firstName": "Alma", "lastName": "Körber", "profession": "FISI", "status": "grün", "applications": 21}
        ]
    },
    {
        "courseName": "IT2024/07",
        "firstLeader": {"firstName": "Peter", "lastName": "Fischer", "gender": "m"},
        "secondLeader": {"firstName": "Laura", "lastName": "Weber", "gender": "f"},
        "students": [
            {"firstName": "Emily", "lastName": "Baumann", "profession": "FIAE", "status": "grün", "applications": 17},
            {"firstName": "Elias", "lastName": "Huber", "profession": "FISI", "status": "gelb", "applications": 10},
            {"firstName": "Amelie", "lastName": "Schuster", "profession": "FIDM", "status": "grün", "applications": 13},
            {"firstName": "Rafael", "lastName": "Böhm", "profession": "FIAE", "status": "rot", "applications": 5},
            {"firstName": "Lilly", "lastName": "Michel", "profession": "FISI", "status": "grün", "applications": 19},
            {"firstName": "Constantin", "lastName": "Brandt", "profession": "FIDM", "status": "gelb", "applications": 11},
            {"firstName": "Romy", "lastName": "Roth", "profession": "FIAE", "status": "grün", "applications": 16},
            {"firstName": "Leopold", "lastName": "Krause", "profession": "FISI", "status": "grün", "applications": 18},
            {"firstName": "Alma", "lastName": "Schmitz", "profession": "FIDM", "status": "rot", "applications": 4},
            {"firstName": "Mattis", "lastName": "Vogt", "profession": "FIAE", "status": "gelb", "applications": 12},
            {"firstName": "Greta", "lastName": "Huber", "profession": "FISI", "status": "grün", "applications": 15},
            {"firstName": "Emil", "lastName": "Groß", "profession": "FIDM", "status": "gelb", "applications": 9},
            {"firstName": "Lina", "lastName": "Winkler", "profession": "FIAE", "status": "grün", "applications": 14},
            {"firstName": "Jakob", "lastName": "König", "profession": "FISI", "status": "rot", "applications": 6},
            {"firstName": "Emilia", "lastName": "Jung", "profession": "FIDM", "status": "grün", "applications": 13},
            {"firstName": "Matteo", "lastName": "Keller", "profession": "FIAE", "status": "gelb", "applications": 8},
            {"firstName": "Lia", "lastName": "Hartmann", "profession": "FISI", "status": "grün", "applications": 20},
            {"firstName": "Milan", "lastName": "Simon", "profession": "FIDM", "status": "gelb", "applications": 10},
            {"firstName": "Zoe", "lastName": "Voigt", "profession": "FIAE", "status": "grün", "applications": 17},
            {"firstName": "Anton", "lastName": "Herrmann", "profession": "FISI", "status": "grün", "applications": 22}
        ]
    },
    {
        "courseName": "IT2025/01",
        "firstLeader": {"firstName": "Sophie", "lastName": "Wagner", "gender": "f"},
        "secondLeader": {"firstName": "Lukas", "lastName": "Becker", "gender": "m"},
        "students": [
            {"firstName": "Maximilian", "lastName": "Graf", "profession": "FIAE", "status": "grün", "applications": 20},
            {"firstName": "Isabella", "lastName": "Köhler", "profession": "FISI", "status": "gelb", "applications": 11},
            {"firstName": "Leo", "lastName": "Stein", "profession": "FIDM", "status": "rot", "applications": 4},
            {"firstName": "Charlotte", "lastName": "Wolf", "profession": "FIAE", "status": "grün", "applications": 18},
            {"firstName": "Henry", "lastName": "Herrmann", "profession": "FISI", "status": "gelb", "applications": 9},
            {"firstName": "Ella", "lastName": "Vogel", "profession": "FIDM", "status": "grün", "applications": 15},
            {"firstName": "Oskar", "lastName": "Brenner", "profession": "FIAE", "status": "rot", "applications": 6},
            {"firstName": "Mila", "lastName": "Eckert", "profession": "FISI", "status": "grün", "applications": 19},
            {"firstName": "Anton", "lastName": "Jäger", "profession": "FIDM", "status": "gelb", "applications": 12},
            {"firstName": "Ida", "lastName": "Bock", "profession": "FIAE", "status": "grün", "applications": 16},
            {"firstName": "Leonard", "lastName": "Baum", "profession": "FISI", "status": "grün", "applications": 17},
            {"firstName": "Clara", "lastName": "Henkel", "profession": "FIDM", "status": "rot", "applications": 5},
            {"firstName": "Theo", "lastName": "Pfeifer", "profession": "FIAE", "status": "gelb", "applications": 13},
            {"firstName": "Emilia", "lastName": "Runge", "profession": "FISI", "status": "grün", "applications": 14},
            {"firstName": "Matteo", "lastName": "Gold", "profession": "FIDM", "status": "gelb", "applications": 10},
            {"firstName": "Lia", "lastName": "Weise", "profession": "FIAE", "status": "grün", "applications": 18},
            {"firstName": "Milan", "lastName": "Bayer", "profession": "FISI", "status": "rot", "applications": 7},
            {"firstName": "Zoe", "lastName": "Grimm", "profession": "FIDM", "status": "grün", "applications": 12},
            {"firstName": "Samuel", "lastName": "Heinz", "profession": "FIAE", "status": "gelb", "applications": 11},
            {"firstName": "Nele", "lastName": "Stark", "profession": "FISI", "status": "grün", "applications": 21}
        ]
    },
    {
        "courseName": "IT2025/07",
        "firstLeader": {"firstName": "Julia", "lastName": "Hoffmann", "gender": "f"},
        "secondLeader": {"firstName": "Tim", "lastName": "Schäfer", "gender": "m"},
        "students": [
            {"firstName": "Charlotte", "lastName": "Vogel", "profession": "FISI", "status": "grün", "applications": 16},
            {"firstName": "Henry", "lastName": "Herrmann", "profession": "FIAE", "status": "gelb", "applications": 9},
            {"firstName": "Emilia", "lastName": "Wolf", "profession": "FIDM", "status": "grün", "applications": 15},
            {"firstName": "Rafael", "lastName": "Sommer", "profession": "FIAE", "status": "rot", "applications": 5},
            {"firstName": "Lilly", "lastName": "Busch", "profession": "FISI", "status": "grün", "applications": 18},
            {"firstName": "Constantin", "lastName": "Ott", "profession": "FIDM", "status": "gelb", "applications": 11},
            {"firstName": "Romy", "lastName": "Schubert", "profession": "FIAE", "status": "grün", "applications": 14},
            {"firstName": "Leopold", "lastName": "Lorenz", "profession": "FISI", "status": "grün", "applications": 19},
            {"firstName": "Alma", "lastName": "Haas", "profession": "FIDM", "status": "rot", "applications": 4},
            {"firstName": "Mattis", "lastName": "Albrecht", "profession": "FIAE", "status": "gelb", "applications": 12},
            {"firstName": "Greta", "lastName": "Seifert", "profession": "FISI", "status": "grün", "applications": 17},
            {"firstName": "Emil", "lastName": "Petersen", "profession": "FIDM", "status": "gelb", "applications": 10},
            {"firstName": "Lina", "lastName": "Riedel", "profession": "FIAE", "status": "grün", "applications": 13},
            {"firstName": "Jakob", "lastName": "Geiger", "profession": "FISI", "status": "rot", "applications": 6},
            {"firstName": "Frieda", "lastName": "Franke", "profession": "FIDM", "status": "grün", "applications": 15},
            {"firstName": "Valentin", "lastName": "Schreiber", "profession": "FIAE", "status": "gelb", "applications": 8},
            {"firstName": "Maja", "lastName": "Wenzel", "profession": "FISI", "status": "grün", "applications": 20},
            {"firstName": "Adrian", "lastName": "Lenz", "profession": "FIDM", "status": "gelb", "applications": 9},
            {"firstName": "Klara", "lastName": "Körber", "profession": "FIAE", "status": "grün", "applications": 16},
            {"firstName": "Vincent", "lastName": "Pohl", "profession": "FISI", "status": "grün", "applications": 22}
        ]
    }
];
