<?php
    //get database data for dashboard
    header('Content-Type => application/json; charset=utf-8');
    $production_mode = filter_var($_POST['prod'], FILTER_VALIDATE_BOOLEAN);
    
    if($production_mode === true){
        //get Db_Data
        $courses = ["DB connection"]; // Hier sollte die tatsächliche Datenbankabfrage stehen
        echo json_encode($courses, JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE);
    } else {
    $courses = [
        [
        "courseName" => "IT2020/01",
        "firstLeader" => ["firstName" => "Thomas", "lastName" => "Bauer", "gender" => "m"],
        "secondLeader" => ["firstName" => "Maria", "lastName" => "Klein", "gender" => "f"],
        "students" => [
            ["firstName" => "Leon", "lastName" => "Wagner", "profession" => "FIAE", "status" => "red"],
            ["firstName" => "Emma", "lastName" => "Koch", "profession" => "FISI", "status" => "red"],
            ["firstName" => "Felix", "lastName" => "Richter", "profession" => "FIDM", "status" => "yellow"],
            ["firstName" => "Hannah", "lastName" => "Groß", "profession" => "FIAE", "status" => "green"],
            ["firstName" => "Jan", "lastName" => "König", "profession" => "FISI", "status" => "red"],
            ["firstName" => "Paula", "lastName" => "Pfeiffer", "profession" => "FIDM", "status" => "yellow"],
            ["firstName" => "Moritz", "lastName" => "Hahn", "profession" => "FIAE", "status" => "green"],
            ["firstName" => "Lara", "lastName" => "Engel", "profession" => "FISI", "status" => "green"],
            ["firstName" => "Simon", "lastName" => "Frank", "profession" => "FIDM", "status" => "red"],
            ["firstName" => "Julia", "lastName" => "Krause", "profession" => "FIAE", "status" => "red"],
            ["firstName" => "Till", "lastName" => "Vogt", "profession" => "FISI", "status" => "red"],
            ["firstName" => "Lea", "lastName" => "Kaiser", "profession" => "FIDM", "status" => "green"],
            ["firstName" => "Nico", "lastName" => "Horn", "profession" => "FIAE", "status" => "yellow"],
            ["firstName" => "Mara", "lastName" => "Sommer", "profession" => "FISI", "status" => "green"],
            ["firstName" => "Erik", "lastName" => "Böhm", "profession" => "FIDM", "status" => "yellow"],
            ["firstName" => "Nora", "lastName" => "Weiß", "profession" => "FIAE", "status" => "red"],
            ["firstName" => "Theo", "lastName" => "Scholz", "profession" => "FISI", "status" => "green"],
            ["firstName" => "Maya", "lastName" => "Friedrich", "profession" => "FIDM", "status" => "green"],
            ["firstName" => "Robin", "lastName" => "Jansen", "profession" => "FIAE", "status" => "yellow"],
            ["firstName" => "Ida", "lastName" => "Stein", "profession" => "FISI", "status" => "green"]
        ]
    ],
    [
        "courseName" => "IT2020/07",
        "firstLeader" => ["firstName" => "Klaus", "lastName" => "Schneider", "gender" => "m"],
        "secondLeader" => ["firstName" => "Petra", "lastName" => "Wolf", "gender" => "f"],
        "students" => [
            ["firstName" => "Lukas", "lastName" => "Schäfer", "profession" => "FISI", "status" => "green"],
            ["firstName" => "Mia", "lastName" => "Becker", "profession" => "FIAE", "status" => "red"],
            ["firstName" => "Noah", "lastName" => "Hoffmann", "profession" => "FIDM", "status" => "yellow"],
            ["firstName" => "Amelie", "lastName" => "Graf", "profession" => "FIAE", "status" => "green"],
            ["firstName" => "Finn", "lastName" => "Baum", "profession" => "FISI", "status" => "yellow"],
            ["firstName" => "Zoe", "lastName" => "Ritter", "profession" => "FIDM", "status" => "green"],
            ["firstName" => "Milan", "lastName" => "Berg", "profession" => "FIAE", "status" => "red"],
            ["firstName" => "Mila", "lastName" => "Winter", "profession" => "FISI", "status" => "green"],
            ["firstName" => "Anton", "lastName" => "Fuchs", "profession" => "FIDM", "status" => "yellow"],
            ["firstName" => "Clara", "lastName" => "Vogel", "profession" => "FIAE", "status" => "green"],
            ["firstName" => "Oskar", "lastName" => "Kraus", "profession" => "FISI", "status" => "green"],
            ["firstName" => "Lia", "lastName" => "Berger", "profession" => "FIDM", "status" => "red"],
            ["firstName" => "Leonard", "lastName" => "Haas", "profession" => "FIAE", "status" => "yellow"],
            ["firstName" => "Emilia", "lastName" => "Schubert", "profession" => "FISI", "status" => "green"],
            ["firstName" => "Matteo", "lastName" => "Lorenz", "profession" => "FIDM", "status" => "yellow"],
            ["firstName" => "Lina", "lastName" => "Kuhn", "profession" => "FIAE", "status" => "green"],
            ["firstName" => "Emil", "lastName" => "Auer", "profession" => "FISI", "status" => "red"],
            ["firstName" => "Charlotte", "lastName" => "Bach", "profession" => "FIDM", "status" => "green"],
            ["firstName" => "Greta", "lastName" => "Lindner", "profession" => "FIAE", "status" => "yellow"],
            ["firstName" => "Jakob", "lastName" => "Brandt", "profession" => "FISI", "status" => "green"]
        ]
    ],
    [
        "courseName" => "IT2021/01",
        "firstLeader" => ["firstName" => "Andreas", "lastName" => "Lehmann", "gender" => "m"],
        "secondLeader" => ["firstName" => "Sandra", "lastName" => "Vogel", "gender" => "f"],
        "students" => [
            ["firstName" => "Sophie", "lastName" => "Kraus", "profession" => "FIAE", "status" => "green"],
            ["firstName" => "Paul", "lastName" => "Zimmermann", "profession" => "FISI", "status" => "yellow"],
            ["firstName" => "Laura", "lastName" => "Braun", "profession" => "FIDM", "status" => "green"],
            ["firstName" => "Elias", "lastName" => "Hofmann", "profession" => "FIAE", "status" => "red"],
            ["firstName" => "Johanna", "lastName" => "Pohl", "profession" => "FISI", "status" => "green"],
            ["firstName" => "David", "lastName" => "Voss", "profession" => "FIDM", "status" => "yellow"],
            ["firstName" => "Ella", "lastName" => "Seidel", "profession" => "FIAE", "status" => "green"],
            ["firstName" => "Felix", "lastName" => "Schuster", "profession" => "FISI", "status" => "green"],
            ["firstName" => "Mia", "lastName" => "Körber", "profession" => "FIDM", "status" => "red"],
            ["firstName" => "Luis", "lastName" => "Ott", "profession" => "FIAE", "status" => "yellow"],
            ["firstName" => "Anna", "lastName" => "Seifert", "profession" => "FISI", "status" => "green"],
            ["firstName" => "Ben", "lastName" => "Albrecht", "profession" => "FIDM", "status" => "yellow"],
            ["firstName" => "Emma", "lastName" => "Lenz", "profession" => "FIAE", "status" => "green"],
            ["firstName" => "Jonas", "lastName" => "Wenzel", "profession" => "FISI", "status" => "red"],
            ["firstName" => "Lena", "lastName" => "Petersen", "profession" => "FIDM", "status" => "green"],
            ["firstName" => "Maximilian", "lastName" => "Bauer", "profession" => "FIAE", "status" => "yellow"],
            ["firstName" => "Hannah", "lastName" => "Riedel", "profession" => "FISI", "status" => "green"],
            ["firstName" => "Noah", "lastName" => "Franke", "profession" => "FIDM", "status" => "green"],
            ["firstName" => "Lea", "lastName" => "Schreiber", "profession" => "FIAE", "status" => "yellow"],
            ["firstName" => "Tim", "lastName" => "Geiger", "profession" => "FISI", "status" => "green"]
        ]
    ],
    [
        "courseName" => "IT2021/07",
        "firstLeader" => ["firstName" => "Michael", "lastName" => "Krüger", "gender" => "m"],
        "secondLeader" => ["firstName" => "Julia", "lastName" => "Hartmann", "gender" => "f"],
        "students" => [
            ["firstName" => "Tim", "lastName" => "Werner", "profession" => "FISI", "status" => "green"],
            ["firstName" => "Hannah", "lastName" => "Lang", "profession" => "FIAE", "status" => "red"],
            ["firstName" => "Ben", "lastName" => "Klein", "profession" => "FIDM", "status" => "yellow"],
            ["firstName" => "Emily", "lastName" => "Stein", "profession" => "FIAE", "status" => "green"],
            ["firstName" => "Leon", "lastName" => "Arnold", "profession" => "FISI", "status" => "yellow"],
            ["firstName" => "Sofia", "lastName" => "Wolff", "profession" => "FIDM", "status" => "green"],
            ["firstName" => "Samuel", "lastName" => "Brandt", "profession" => "FIAE", "status" => "red"],
            ["firstName" => "Mila", "lastName" => "Simon", "profession" => "FISI", "status" => "green"],
            ["firstName" => "Henry", "lastName" => "Böhm", "profession" => "FIDM", "status" => "yellow"],
            ["firstName" => "Lara", "lastName" => "Michel", "profession" => "FIAE", "status" => "green"],
            ["firstName" => "Niklas", "lastName" => "König", "profession" => "FISI", "status" => "green"],
            ["firstName" => "Clara", "lastName" => "Keller", "profession" => "FIDM", "status" => "red"],
            ["firstName" => "Julian", "lastName" => "Jung", "profession" => "FIAE", "status" => "yellow"],
            ["firstName" => "Amelie", "lastName" => "Roth", "profession" => "FISI", "status" => "green"],
            ["firstName" => "Fabian", "lastName" => "Krause", "profession" => "FIDM", "status" => "yellow"],
            ["firstName" => "Maja", "lastName" => "Huber", "profession" => "FIAE", "status" => "green"],
            ["firstName" => "Luca", "lastName" => "Schmitz", "profession" => "FISI", "status" => "red"],
            ["firstName" => "Frieda", "lastName" => "Voigt", "profession" => "FIDM", "status" => "green"],
            ["firstName" => "Theo", "lastName" => "Winkler", "profession" => "FIAE", "status" => "yellow"],
            ["firstName" => "Isabella", "lastName" => "Groß", "profession" => "FISI", "status" => "green"]
        ]
    ],
    [
        "courseName" => "IT2022/01",
        "firstLeader" => ["firstName" => "Stefan", "lastName" => "Neumann", "gender" => "m"],
        "secondLeader" => ["firstName" => "Claudia", "lastName" => "Möller", "gender" => "f"],
        "students" => [
            ["firstName" => "Jana", "lastName" => "Schulz", "profession" => "FIAE", "status" => "green"],
            ["firstName" => "Max", "lastName" => "Friedrich", "profession" => "FISI", "status" => "yellow"],
            ["firstName" => "Lena", "lastName" => "Berger", "profession" => "FIDM", "status" => "green"],
            ["firstName" => "Oliver", "lastName" => "Herzog", "profession" => "FIAE", "status" => "red"],
            ["firstName" => "Sarah", "lastName" => "Vogt", "profession" => "FISI", "status" => "green"],
            ["firstName" => "Moritz", "lastName" => "Bender", "profession" => "FIDM", "status" => "yellow"],
            ["firstName" => "Nele", "lastName" => "Kaiser", "profession" => "FIAE", "status" => "green"],
            ["firstName" => "Tobias", "lastName" => "Lehmann", "profession" => "FISI", "status" => "green"],
            ["firstName" => "Paula", "lastName" => "Sauer", "profession" => "FIDM", "status" => "red"],
            ["firstName" => "Simon", "lastName" => "Engel", "profession" => "FIAE", "status" => "yellow"],
            ["firstName" => "Julia", "lastName" => "Böttcher", "profession" => "FISI", "status" => "green"],
            ["firstName" => "Erik", "lastName" => "Hahn", "profession" => "FIDM", "status" => "yellow"],
            ["firstName" => "Klara", "lastName" => "Kunz", "profession" => "FIAE", "status" => "green"],
            ["firstName" => "Robin", "lastName" => "Schröder", "profession" => "FISI", "status" => "red"],
            ["firstName" => "Ida", "lastName" => "Horn", "profession" => "FIDM", "status" => "green"],
            ["firstName" => "Vincent", "lastName" => "Fiedler", "profession" => "FIAE", "status" => "yellow"],
            ["firstName" => "Marlene", "lastName" => "Nagel", "profession" => "FISI", "status" => "green"],
            ["firstName" => "Anton", "lastName" => "Ziegler", "profession" => "FIDM", "status" => "yellow"],
            ["firstName" => "Mira", "lastName" => "Pfeiffer", "profession" => "FIAE", "status" => "green"],
            ["firstName" => "Adrian", "lastName" => "Förster", "profession" => "FISI", "status" => "green"]
        ]
    ],
    [
        "courseName" => "IT2022/07",
        "firstLeader" => ["firstName" => "Daniel", "lastName" => "Schmitt", "gender" => "m"],
        "secondLeader" => ["firstName" => "Katrin", "lastName" => "Meier", "gender" => "f"],
        "students" => [
            ["firstName" => "David", "lastName" => "Walter", "profession" => "FISI", "status" => "green"],
            ["firstName" => "Nina", "lastName" => "Peters", "profession" => "FIAE", "status" => "red"],
            ["firstName" => "Erik", "lastName" => "Schwarz", "profession" => "FIDM", "status" => "yellow"],
            ["firstName" => "Lisa", "lastName" => "Heinz", "profession" => "FIAE", "status" => "green"],
            ["firstName" => "Tom", "lastName" => "Busch", "profession" => "FISI", "status" => "yellow"],
            ["firstName" => "Emely", "lastName" => "Stark", "profession" => "FIDM", "status" => "green"],
            ["firstName" => "Lukas", "lastName" => "Sommer", "profession" => "FIAE", "status" => "red"],
            ["firstName" => "Marie", "lastName" => "Gold", "profession" => "FISI", "status" => "green"],
            ["firstName" => "Jacob", "lastName" => "Weise", "profession" => "FIDM", "status" => "yellow"],
            ["firstName" => "Elena", "lastName" => "Bayer", "profession" => "FIAE", "status" => "green"],
            ["firstName" => "Rafael", "lastName" => "Grimm", "profession" => "FISI", "status" => "green"],
            ["firstName" => "Sophia", "lastName" => "Eckert", "profession" => "FIDM", "status" => "red"],
            ["firstName" => "Constantin", "lastName" => "Jäger", "profession" => "FIAE", "status" => "yellow"],
            ["firstName" => "Lilly", "lastName" => "Franke", "profession" => "FISI", "status" => "green"],
            ["firstName" => "Mattis", "lastName" => "Bock", "profession" => "FIDM", "status" => "yellow"],
            ["firstName" => "Frieda", "lastName" => "Baum", "profession" => "FIAE", "status" => "green"],
            ["firstName" => "Leopold", "lastName" => "Henkel", "profession" => "FISI", "status" => "red"],
            ["firstName" => "Romy", "lastName" => "Pfeifer", "profession" => "FIDM", "status" => "green"],
            ["firstName" => "Valentin", "lastName" => "Runge", "profession" => "FIAE", "status" => "yellow"],
            ["firstName" => "Alma", "lastName" => "Brenner", "profession" => "FISI", "status" => "green"]
        ]
    ],
    [
        "courseName" => "IT2023/01",
        "firstLeader" => ["firstName" => "Max", "lastName" => "Mustermann", "gender" => "m"],
        "secondLeader" => ["firstName" => "Erika", "lastName" => "Musterfrau", "gender" => "f"],
        "students" => [
            ["firstName" => "Anna", "lastName" => "Schmidt", "profession" => "FIAE", "status" => "green"],
            ["firstName" => "Tom", "lastName" => "Meyer", "profession" => "FISI", "status" => "yellow"],
            ["firstName" => "Lisa", "lastName" => "Müller", "profession" => "FIDM", "status" => "red"],
            ["firstName" => "Jonas", "lastName" => "Weber", "profession" => "FIAE", "status" => "green"],
            ["firstName" => "Sarah", "lastName" => "Fischer", "profession" => "FISI", "status" => "green"],
            ["firstName" => "Felix", "lastName" => "Wagner", "profession" => "FIDM", "status" => "yellow"],
            ["firstName" => "Laura", "lastName" => "Becker", "profession" => "FIAE", "status" => "green"],
            ["firstName" => "Lukas", "lastName" => "Schulz", "profession" => "FISI", "status" => "red"],
            ["firstName" => "Emma", "lastName" => "Hoffmann", "profession" => "FIDM", "status" => "yellow"],
            ["firstName" => "Paul", "lastName" => "Koch", "profession" => "FIAE", "status" => "green"],
            ["firstName" => "Sophie", "lastName" => "Richter", "profession" => "FISI", "status" => "green"],
            ["firstName" => "Maximilian", "lastName" => "Schröder", "profession" => "FIDM", "status" => "yellow"],
            ["firstName" => "Hannah", "lastName" => "Neumann", "profession" => "FIAE", "status" => "red"],
            ["firstName" => "Leon", "lastName" => "Krause", "profession" => "FISI", "status" => "green"],
            ["firstName" => "Mia", "lastName" => "Lange", "profession" => "FIDM", "status" => "yellow"],
            ["firstName" => "Noah", "lastName" => "Schmitt", "profession" => "FIAE", "status" => "green"],
            ["firstName" => "Lena", "lastName" => "Werner", "profession" => "FISI", "status" => "red"],
            ["firstName" => "David", "lastName" => "Krüger", "profession" => "FIDM", "status" => "green"],
            ["firstName" => "Emily", "lastName" => "Hartmann", "profession" => "FIAE", "status" => "yellow"],
            ["firstName" => "Finn", "lastName" => "Zimmermann", "profession" => "FISI", "status" => "green"]
        ]
    ],
    [
        "courseName" => "IT2023/07",
        "firstLeader" => ["firstName" => "Peter", "lastName" => "Maier", "gender" => "m"],
        "secondLeader" => ["firstName" => "Sabine", "lastName" => "Roth", "gender" => "f"],
        "students" => [
            ["firstName" => "Marie", "lastName" => "Jung", "profession" => "FIAE", "status" => "green"],
            ["firstName" => "Finn", "lastName" => "Lange", "profession" => "FISI", "status" => "yellow"],
            ["firstName" => "Clara", "lastName" => "Frank", "profession" => "FIDM", "status" => "green"],
            ["firstName" => "Henry", "lastName" => "Braun", "profession" => "FIAE", "status" => "red"],
            ["firstName" => "Ella", "lastName" => "Klein", "profession" => "FISI", "status" => "green"],
            ["firstName" => "Oskar", "lastName" => "Winter", "profession" => "FIDM", "status" => "yellow"],
            ["firstName" => "Mila", "lastName" => "Seidel", "profession" => "FIAE", "status" => "green"],
            ["firstName" => "Anton", "lastName" => "Vogel", "profession" => "FISI", "status" => "green"],
            ["firstName" => "Ida", "lastName" => "Kaiser", "profession" => "FIDM", "status" => "red"],
            ["firstName" => "Leonard", "lastName" => "Graf", "profession" => "FIAE", "status" => "yellow"],
            ["firstName" => "Charlotte", "lastName" => "Bergmann", "profession" => "FISI", "status" => "green"],
            ["firstName" => "Theo", "lastName" => "Schuster", "profession" => "FIDM", "status" => "yellow"],
            ["firstName" => "Greta", "lastName" => "Ott", "profession" => "FIAE", "status" => "green"],
            ["firstName" => "Emil", "lastName" => "Busch", "profession" => "FISI", "status" => "red"],
            ["firstName" => "Lina", "lastName" => "Schubert", "profession" => "FIDM", "status" => "green"],
            ["firstName" => "Jakob", "lastName" => "Voigt", "profession" => "FIAE", "status" => "yellow"],
            ["firstName" => "Emilia", "lastName" => "Herrmann", "profession" => "FISI", "status" => "green"],
            ["firstName" => "Matteo", "lastName" => "Keller", "profession" => "FIDM", "status" => "yellow"],
            ["firstName" => "Lia", "lastName" => "Simon", "profession" => "FIAE", "status" => "green"],
            ["firstName" => "Milan", "lastName" => "Winkler", "profession" => "FISI", "status" => "green"]
        ]
    ],
    [
        "courseName" => "IT2024/01",
        "firstLeader" => ["firstName" => "Hans", "lastName" => "Müller", "gender" => "m"],
        "secondLeader" => ["firstName" => "Anna", "lastName" => "Schmidt", "gender" => "f"],
        "students" => [
            ["firstName" => "Oliver", "lastName" => "Schulze", "profession" => "FISI", "status" => "green"],
            ["firstName" => "Sophia", "lastName" => "Hoffmann", "profession" => "FIAE", "status" => "red"],
            ["firstName" => "Luis", "lastName" => "Becker", "profession" => "FIDM", "status" => "yellow"],
            ["firstName" => "Isabella", "lastName" => "Arnold", "profession" => "FIAE", "status" => "green"],
            ["firstName" => "Leo", "lastName" => "Werner", "profession" => "FISI", "status" => "yellow"],
            ["firstName" => "Amelie", "lastName" => "Fuchs", "profession" => "FIDM", "status" => "green"],
            ["firstName" => "Samuel", "lastName" => "Lorenz", "profession" => "FIAE", "status" => "red"],
            ["firstName" => "Johanna", "lastName" => "Berger", "profession" => "FISI", "status" => "green"],
            ["firstName" => "Elias", "lastName" => "Haas", "profession" => "FIDM", "status" => "yellow"],
            ["firstName" => "Nele", "lastName" => "Albrecht", "profession" => "FIAE", "status" => "green"],
            ["firstName" => "Julian", "lastName" => "Seifert", "profession" => "FISI", "status" => "green"],
            ["firstName" => "Klara", "lastName" => "Petersen", "profession" => "FIDM", "status" => "red"],
            ["firstName" => "Vincent", "lastName" => "Riedel", "profession" => "FIAE", "status" => "yellow"],
            ["firstName" => "Marlene", "lastName" => "Bauer", "profession" => "FISI", "status" => "green"],
            ["firstName" => "Robin", "lastName" => "Geiger", "profession" => "FIDM", "status" => "yellow"],
            ["firstName" => "Maja", "lastName" => "Franke", "profession" => "FIAE", "status" => "green"],
            ["firstName" => "Adrian", "lastName" => "Schreiber", "profession" => "FISI", "status" => "red"],
            ["firstName" => "Frieda", "lastName" => "Wenzel", "profession" => "FIDM", "status" => "green"],
            ["firstName" => "Valentin", "lastName" => "Lenz", "profession" => "FIAE", "status" => "yellow"],
            ["firstName" => "Alma", "lastName" => "Körber", "profession" => "FISI", "status" => "green"]
        ]
    ],
    [
        "courseName" => "IT2024/07",
        "firstLeader" => ["firstName" => "Peter", "lastName" => "Fischer", "gender" => "m"],
        "secondLeader" => ["firstName" => "Laura", "lastName" => "Weber", "gender" => "f"],
        "students" => [
            ["firstName" => "Emily", "lastName" => "Baumann", "profession" => "FIAE", "status" => "green"],
            ["firstName" => "Elias", "lastName" => "Huber", "profession" => "FISI", "status" => "yellow"],
            ["firstName" => "Amelie", "lastName" => "Schuster", "profession" => "FIDM", "status" => "green"],
            ["firstName" => "Rafael", "lastName" => "Böhm", "profession" => "FIAE", "status" => "red"],
            ["firstName" => "Lilly", "lastName" => "Michel", "profession" => "FISI", "status" => "green"],
            ["firstName" => "Constantin", "lastName" => "Brandt", "profession" => "FIDM", "status" => "yellow"],
            ["firstName" => "Romy", "lastName" => "Roth", "profession" => "FIAE", "status" => "green"],
            ["firstName" => "Leopold", "lastName" => "Krause", "profession" => "FISI", "status" => "green"],
            ["firstName" => "Alma", "lastName" => "Schmitz", "profession" => "FIDM", "status" => "red"],
            ["firstName" => "Mattis", "lastName" => "Vogt", "profession" => "FIAE", "status" => "yellow"],
            ["firstName" => "Greta", "lastName" => "Huber", "profession" => "FISI", "status" => "green"],
            ["firstName" => "Emil", "lastName" => "Groß", "profession" => "FIDM", "status" => "yellow"],
            ["firstName" => "Lina", "lastName" => "Winkler", "profession" => "FIAE", "status" => "green"],
            ["firstName" => "Jakob", "lastName" => "König", "profession" => "FISI", "status" => "red"],
            ["firstName" => "Emilia", "lastName" => "Jung", "profession" => "FIDM", "status" => "green"],
            ["firstName" => "Matteo", "lastName" => "Keller", "profession" => "FIAE", "status" => "yellow"],
            ["firstName" => "Lia", "lastName" => "Hartmann", "profession" => "FISI", "status" => "green"],
            ["firstName" => "Milan", "lastName" => "Simon", "profession" => "FIDM", "status" => "yellow"],
            ["firstName" => "Zoe", "lastName" => "Voigt", "profession" => "FIAE", "status" => "green"],
            ["firstName" => "Anton", "lastName" => "Herrmann", "profession" => "FISI", "status" => "green"]
        ]
    ],
    [
        "courseName" => "IT2025/01",
        "firstLeader" => ["firstName" => "Sophie", "lastName" => "Wagner", "gender" => "f"],
        "secondLeader" => ["firstName" => "Lukas", "lastName" => "Becker", "gender" => "m"],
        "students" => [
            ["firstName" => "Maximilian", "lastName" => "Graf", "profession" => "FIAE", "status" => "green"],
            ["firstName" => "Isabella", "lastName" => "Köhler", "profession" => "FISI", "status" => "yellow"],
            ["firstName" => "Leo", "lastName" => "Stein", "profession" => "FIDM", "status" => "red"],
            ["firstName" => "Charlotte", "lastName" => "Wolf", "profession" => "FIAE", "status" => "green"],
            ["firstName" => "Henry", "lastName" => "Herrmann", "profession" => "FISI", "status" => "yellow"],
            ["firstName" => "Ella", "lastName" => "Vogel", "profession" => "FIDM", "status" => "green"],
            ["firstName" => "Oskar", "lastName" => "Brenner", "profession" => "FIAE", "status" => "red"],
            ["firstName" => "Mila", "lastName" => "Eckert", "profession" => "FISI", "status" => "green"],
            ["firstName" => "Anton", "lastName" => "Jäger", "profession" => "FIDM", "status" => "yellow"],
            ["firstName" => "Ida", "lastName" => "Bock", "profession" => "FIAE", "status" => "green"],
            ["firstName" => "Leonard", "lastName" => "Baum", "profession" => "FISI", "status" => "green"],
            ["firstName" => "Clara", "lastName" => "Henkel", "profession" => "FIDM", "status" => "red"],
            ["firstName" => "Theo", "lastName" => "Pfeifer", "profession" => "FIAE", "status" => "yellow"],
            ["firstName" => "Emilia", "lastName" => "Runge", "profession" => "FISI", "status" => "green"],
            ["firstName" => "Matteo", "lastName" => "Gold", "profession" => "FIDM", "status" => "yellow"],
            ["firstName" => "Lia", "lastName" => "Weise", "profession" => "FIAE", "status" => "green"],
            ["firstName" => "Milan", "lastName" => "Bayer", "profession" => "FISI", "status" => "red"],
            ["firstName" => "Zoe", "lastName" => "Grimm", "profession" => "FIDM", "status" => "green"],
            ["firstName" => "Samuel", "lastName" => "Heinz", "profession" => "FIAE", "status" => "yellow"],
            ["firstName" => "Nele", "lastName" => "Stark", "profession" => "FISI", "status" => "green"]
        ]
    ],
    [
        "courseName" => "IT2025/07",
        "firstLeader" => ["firstName" => "Julia", "lastName" => "Hoffmann", "gender" => "f"],
        "secondLeader" => ["firstName" => "Tim", "lastName" => "Schäfer", "gender" => "m"],
        "students" => [
            ["firstName" => "Charlotte", "lastName" => "Vogel", "profession" => "FISI", "status" => "green"],
            ["firstName" => "Henry", "lastName" => "Herrmann", "profession" => "FIAE", "status" => "yellow"],
            ["firstName" => "Emilia", "lastName" => "Wolf", "profession" => "FIDM", "status" => "green"],
            ["firstName" => "Rafael", "lastName" => "Sommer", "profession" => "FIAE", "status" => "red"],
            ["firstName" => "Lilly", "lastName" => "Busch", "profession" => "FISI", "status" => "green"],
            ["firstName" => "Constantin", "lastName" => "Ott", "profession" => "FIDM", "status" => "yellow"],
            ["firstName" => "Romy", "lastName" => "Schubert", "profession" => "FIAE", "status" => "green"],
            ["firstName" => "Leopold", "lastName" => "Lorenz", "profession" => "FISI", "status" => "green"],
            ["firstName" => "Alma", "lastName" => "Haas", "profession" => "FIDM", "status" => "red"],
            ["firstName" => "Mattis", "lastName" => "Albrecht", "profession" => "FIAE", "status" => "yellow"],
            ["firstName" => "Greta", "lastName" => "Seifert", "profession" => "FISI", "status" => "green"],
            ["firstName" => "Emil", "lastName" => "Petersen", "profession" => "FIDM", "status" => "yellow"],
            ["firstName" => "Lina", "lastName" => "Riedel", "profession" => "FIAE", "status" => "green"],
            ["firstName" => "Jakob", "lastName" => "Geiger", "profession" => "FISI", "status" => "red"],
            ["firstName" => "Frieda", "lastName" => "Franke", "profession" => "FIDM", "status" => "green"],
            ["firstName" => "Valentin", "lastName" => "Schreiber", "profession" => "FIAE", "status" => "yellow"],
            ["firstName" => "Maja", "lastName" => "Wenzel", "profession" => "FISI", "status" => "green"],
            ["firstName" => "Adrian", "lastName" => "Lenz", "profession" => "FIDM", "status" => "yellow"],
            ["firstName" => "Klara", "lastName" => "Körber", "profession" => "FIAE", "status" => "green"],
            ["firstName" => "Vincent", "lastName" => "Pohl", "profession" => "FISI", "status" => "green"]
        ]
    ]
];
echo json_encode($courses, JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE);
}
    
?>

